sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --reruns 0 presentation.tex; tectonic --reruns 0 talk.tex;"

after_success:
  - mv presentation.pdf presentation-${TRAVIS_TAG}.pdf
  - mv talk.pdf talk-${TRAVIS_TAG}.pdf

deploy:
  provider: releases
  api_key:
    secure: qBQ8GHfMluW4GpYOkNVAAsWTQfj+3LVkKkZN8wTOhUyM7H8w/pcHnujGoClEzP0onefNKE7I5RPltKwHkoZAmBwVzkEW/ZXS2t8UIXPzVXKiP4wHhW9/NMftcN2Pk8KZQ72tvvP/nGOMH0T9jSeBbvG1KUI//V4Tv3F4GcU74Caig1XdJ661OontZjBdmRXG8ei4C4gpBaCNZMZ2M2hvelBo2+XkBp1ksP0W1u87nCzIP1pa8cHGnaP2D8Xg0fXZ/NDWQYwkdWgZ4FCf1L91x/GV4cukQGMgzgKEPq0omvV8KCmV4TNfEnX62f3fva9he/8edZqu18JPH2Sey3q2Sbb52bpBrUz0i/LFschUbrl03uGjGyKsn2ix1Fo5yuZtCBwsW2RzvZtKGAwhVVpUxWvrSh9Hu4Rros57+TzOi2/BVKCbEWgzujep3zp0Tin3/V5AJPJ6L+dp86CWHKNg7riWj9Ekmhi1Pi3r/DHKJJpkbZuXnEKXKQzDg4mA5ufo0tnFWgtoywposkUv6OwqAGZ3Xj92r90uSGpZSKXQ+m6qaHsSVVbYFMLdOplkV8KOIeoj2e4WrUcEW+VK4Ti4FlJXA5KZgY4ofWuXDhVF5Lt6H6m/G6ysOpeSs13tn5sXsHqxLlyOpH9lku+oowfPoXF8KPX+AOP3+Wb7d52wMMU=
  file: 
    - $TRAVIS_BUILD_DIR/presentation-${TRAVIS_TAG}.pdf
    - $TRAVIS_BUILD_DIR/talk-${TRAVIS_TAG}.pdf
  skip_cleanup: true
  on:
    repo: lparolari/bachelor-thesis-presentation
    tags: true
