sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 presentation.tex; tectonic --reruns 0 presentation.tex; tectonic --reruns 0 talk.tex;"

after_success:
  - mv presentation.pdf presentation-${TRAVIS_TAG}.pdf
  - mv talk.pdf talk-${TRAVIS_TAG}.pdf

deploy:
  provider: releases
  api_key:
    secure: J4GcHtsiT/EgjocJH51U63bmRA6T9T5wflVoSjVvtSBsT8bvM6RixuvHZ/EwJCDcVd+X8fVoGavfHhf74RDUnfuiSGVeVyLIA4kMLMkxlJ0v1ReP7uU08yPS/xWlOFoE/FZ6S6P7CfGf3rQwySC+2jny4AYQWbXMD7biVfTZxwX0xuTanjqn3RsVDOuJuokZSuPwCOWjXCCR9AQHPu8BMvjGxiY4dETkVtdJ0+FNnFKR8kRgFKJDt5pNRjkBQe6ykPX4+R6/cEuY6V46j9KMBU+NaSUFR3KK1Kna+UBq/X18eDluV0u2TVpBU6v5drgvErpb1zQrITgzgr0mufZfPQewztQaOpBpmI3u5StztQKXIzs7oBGU+Dasx7lOOwhTpJajjffmfR/5nrKK2M4aD9XvIXbzaeHmO+WZY069C+1CWn8owKFnEzX0Sih//vC6PP7GV41Jq3jnKgeKmMkzIvKlvb++/fGSp1V+fp1Dz8Z41F/BAnPsv636FCCehl1OU55zoXpAmAdFclJGDl+kNpsKCxaTXhtOBWcJXkKix9sXouOWQA2EU/1Rwq68vl1LiPhwwZWBcBR5+N1lpiMdjmVp0j2PCHynUNSGNUxxElPEqA25GBwAf+ISiE6KKygoBRsglOeYFTWjkUZ2ksihxPPjP9cpn2vk4iWksay7zoo=
  file: 
    - $TRAVIS_BUILD_DIR/presentation-${TRAVIS_TAG}.pdf
    - $TRAVIS_BUILD_DIR/talk-${TRAVIS_TAG}.pdf
  skip_cleanup: true
  on:
    repo: lparolari/bachelor-thesis-presentation
    tags: true
